#!/usr/bin/env bash
# provision.sh — one-shot machine-layer provisioning for a GCP GPU box (Ubuntu 24.04)
# for the racecast cloud-producer spike (#395).
#
# Installs everything racecast does NOT cover — NVIDIA driver, xfce desktop,
# Firefox (deb, not snap), RustDesk, passwordless sudo, Tailscale join — then delegates
# the toolchain + applications to the racecast binary (install-tools / install-apps).
#
# Idempotent: every step is existence-/stamp-gated; safe to re-run after a failure.
# Runs as root: `sudo ./provision.sh`, or as a GCP startup-script (instance metadata).
#
# Optional environment:
#   TS_AUTHKEY        Tailscale reusable/ephemeral pre-auth key for unattended join.
#                     NEVER commit this. The tailnet join is REQUIRED (step 10): with a key
#                     it is unattended; run interactively without a key and step 10 performs
#                     the browser-auth join (prints a login URL to approve in your laptop
#                     browser, and WAITS); only a non-interactive run without a key defers it
#                     to a one-line command the operator must run once.
#   RACECAST_TAG      racecast release tag to install (default: latest = latest STABLE
#                     release). Set to `preview-main` to install the current main
#                     preview build — needed until the Linux install-tools/install-apps
#                     fixes land in a stable release: apt-update-first (#408/#412) AND
#                     the streamlink-venv >=8.2.0 + obs-pipewire-audio plugin installs
#                     (#395). Without them a fresh box gets a too-old streamlink (every
#                     cookie'd YouTube feed aborts) and no Discord audio plugin.
#                     `latest` never selects a pre-release, so this is opt-in.
#   RUSTDESK_VERSION  RustDesk release to install (default: pinned below; check for newer).
#
# NOT handled here — per-league onboarding the operator does once per league:
#   racecast profiles, cookies, `racecast setup`, OBS scene import, RustDesk password.

set -euo pipefail

RUSTDESK_VERSION="${RUSTDESK_VERSION:-1.3.8}"
RACECAST_REPO="jegr78/gt-endurance-racing-broadcast"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '  \033[1;32mOK\033[0m  %s\n' "$*"; }
warn() { printf '  \033[1;33m!!\033[0m  %s\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }
has_nvidia_gpu() { lspci 2>/dev/null | grep -i 'nvidia' >/dev/null; }   # SIGPIPE-safe (no -q early close under pipefail); false on a CPU-only dry-run box

# Resolve the NVIDIA card's PCI slot (DDDD:BB:DD.F, hex) to an Xorg BusID
# (PCI:bus:dev:fn, DECIMAL). Differs per instance, so read it live. Empty -> caller warns.
gpu_pci_bus_id() {
  local slot bus dev fn
  slot="$(lspci -D 2>/dev/null | grep -iE 'nvidia' | grep -iE 'VGA|3D|Display' | head -1 | awk '{print $1}')"
  [ -n "$slot" ] || return 1
  slot="${slot#*:}"          # strip domain -> BB:DD.F
  bus="${slot%%:*}"          # BB
  dev="${slot#*:}"; dev="${dev%%.*}"   # DD
  fn="${slot#*.}"            # F
  printf 'PCI:%d:%d:%d' "0x$bus" "0x$dev" "0x$fn"
}

# Write a headless Xorg config: a single 1920x1080 mode with a matching Virtual size
# (NOT larger — a bigger Virtual creates a +offset viewport that breaks RustDesk's
# absolute pointer mapping), forcing a virtual DFP so X comes up with no monitor.
write_headless_xorg() {
  local bus_id="$1"
  cat > /etc/X11/xorg.conf <<EOF
# racecast headless X (generated by provision.sh) — single 1920x1080, no monitor.
Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
EndSection

Section "Device"
    Identifier "Device0"
    Driver     "nvidia"
    BusID      "$bus_id"
    Option     "AllowEmptyInitialConfiguration" "true"
    Option     "ConnectedMonitor" "DFP-0"
    Option     "ModeValidation" "AllowNonEdidModes"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    HorizSync  28.0 - 80.0
    VertRefresh 48.0 - 75.0
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Device0"
    Monitor    "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Depth  24
        Modes  "1920x1080"
        Virtual 1920 1080
    EndSubSection
EndSection
EOF
}

# GUI autostart so `racecast event start` over SSH finds OBS + Discord already
# running in the autologin session (belt-and-suspenders with event start's
# DISPLAY=:0 launch). Harmless if a binary is absent — the entry just no-ops.
write_gui_autostart() {
  local user_home="$1" user_name="$2"
  install -d -o "$user_name" -g "$user_name" "$user_home/.config/autostart"
  cat > "$user_home/.config/autostart/racecast-obs.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=OBS Studio (racecast)
Exec=obs
X-GNOME-Autostart-enabled=true
EOF
  cat > "$user_home/.config/autostart/racecast-discord.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=Discord (racecast)
Exec=discord
X-GNOME-Autostart-enabled=true
EOF
  chown "$user_name:$user_name" \
    "$user_home/.config/autostart/racecast-obs.desktop" \
    "$user_home/.config/autostart/racecast-discord.desktop"
}

# Write the first-boot RustDesk setup helper. RustDesk's password / ID / direct-IP toggle
# need the user's GRAPHICAL session (rustdesk spawns --server inside it), which only comes
# up after the first reboot (autologin). So provision cannot set them inline; instead this
# root helper runs once from a systemd oneshot After=graphical.target: it sets the password
# (from /etc/racecast/rustdesk-password), best-effort enables direct IP access, and writes
# the ID + password to ~USER/rustdesk-access.txt for the operator. No GUI, no manual step.
write_rustdesk_setup_helper() {
  local user_name="$1"
  cat > /usr/local/sbin/racecast-rustdesk-setup <<'HELPER'
#!/usr/bin/env bash
# Managed by racecast provision.sh — configures RustDesk once the desktop session is up.
set -u
USER_NAME="__USER__"
uid="$(id -u "$USER_NAME" 2>/dev/null)" || exit 0
run_as_user() { sudo -u "$USER_NAME" DISPLAY=:0 XDG_RUNTIME_DIR="/run/user/$uid" "$@"; }
# Wait for the rustdesk server (spawned in the user session) to answer with an ID.
rid=""
for _ in $(seq 1 30); do
  rid="$(run_as_user rustdesk --get-id 2>/dev/null | tr -dc '0-9')"
  [ -n "$rid" ] && break
  sleep 2
done
pw="$(cat /etc/racecast/rustdesk-password 2>/dev/null)"
[ -n "$pw" ] && rustdesk --password "$pw" >/dev/null 2>&1
# Best-effort: enable direct IP access over the tailnet (a no-op on builds that gate it).
run_as_user rustdesk --option direct-server Y >/dev/null 2>&1 || true
ip="$(tailscale ip -4 2>/dev/null | head -1)"
out="/home/$USER_NAME/rustdesk-access.txt"
{
  echo "RustDesk access for this box (user: $USER_NAME) — generated on first boot."
  echo "  ID:        ${rid:-<run: rustdesk --get-id>}"
  echo "  Password:  ${pw:-<unset — set /etc/racecast/rustdesk-password + re-run>}"
  echo "  Tailnet:   ${ip:-<tailscale ip -4>}"
  echo "Connect from your laptop's RustDesk with the ID + password."
} > "$out"
chown "$USER_NAME:$(id -gn "$USER_NAME")" "$out" 2>/dev/null || true
chmod 0600 "$out" 2>/dev/null || true
install -d /var/lib/racecast; : > /var/lib/racecast/rustdesk-configured
HELPER
  sed -i "s/__USER__/$user_name/" /usr/local/sbin/racecast-rustdesk-setup
  chmod 0755 /usr/local/sbin/racecast-rustdesk-setup
}

if [ "$(id -u)" -ne 0 ]; then
  echo "provision.sh must run as root (use: sudo ./provision.sh)" >&2
  exit 1
fi

# The event stack runs as a dedicated `racecast` user — the box's single operational
# account. provision ENSURES it exists and TARGETS it for everything below, so the
# autologin X session (which RustDesk mirrors on :0), OBS, the sudoers rule, and the
# install tree ALL run as `racecast` deterministically — regardless of which account
# happened to launch provision. You then log in DIRECTLY as this user at event time
# (`gcloud compute ssh racecast@racecast-box`; OS Login off → the guest agent adds your
# key to `racecast` on first connect), so operating the box is plain `racecast <cmd>` —
# ONE user, no `sudo -iu`. Override the name with RACECAST_USER=... if ever needed.
RACECAST_USER="${RACECAST_USER:-racecast}"
if ! getent passwd "$RACECAST_USER" >/dev/null; then
  useradd -m -s /bin/bash "$RACECAST_USER"
  ok "created event user $RACECAST_USER (home $(getent passwd "$RACECAST_USER" | cut -d: -f6))"
fi
# Groups OBS/NVENC/PipeWire need: render+video (GPU /dev/nvidia* + NVENC), audio
# (PipeWire capture). Harmless when a group is absent on this image.
for g in video render audio plugdev; do
  getent group "$g" >/dev/null && usermod -aG "$g" "$RACECAST_USER" || true
done
USER_NAME="$RACECAST_USER"

# ---------------------------------------------------------------------------
log "1/10  APT base + upgrade"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y upgrade
# python3-venv + python3-pip: racecast install-tools builds an isolated streamlink
# venv on Linux (apt's streamlink is too old for --http-cookies-file, #350/#395).
# mesa-utils: glxinfo for the headless-X verification; x11-utils: xdpyinfo debug aid.
apt-get install -y curl python3 python3-venv python3-pip ca-certificates wget gnupg pciutils mesa-utils x11-utils
ok "base packages present"

# ---------------------------------------------------------------------------
log "2/10  NVIDIA driver (nvidia-open via CUDA apt repo) + headless X config"
# Why NOT GoogleCloudPlatform/install_gpu_driver.py: it pins driver 550.54.15, whose
# proprietary kernel modules FAIL to build against Ubuntu 24.04's current HWE kernel
# (6.17) — the box hit exactly this. The NVIDIA CUDA apt repo's `nvidia-open` (open
# kernel modules, DKMS-built) builds cleanly on new kernels. (#395, live-verified.)
if ! has_nvidia_gpu; then
  warn "no NVIDIA GPU on this host — skipping driver + xorg (CPU dry-run mode)"
elif nvidia-smi >/dev/null 2>&1; then
  ok "driver already loaded ($(nvidia-smi --query-gpu=name --format=csv,noheader | head -1))"
else
  case "$(uname -m)" in
    aarch64|arm64) cuda_arch="sbsa" ;;
    *)             cuda_arch="x86_64" ;;
  esac
  if [ ! -f /etc/apt/sources.list.d/cuda-ubuntu2404-"$cuda_arch".list ] \
     && ! apt-key list 2>/dev/null | grep -qi cuda; then
    curl -fsSL "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/${cuda_arch}/cuda-keyring_1.1-1_all.deb" -o /tmp/cuda-keyring.deb
    dpkg -i /tmp/cuda-keyring.deb
    apt-get update
  fi
  apt-get install -y nvidia-open || warn "nvidia-open apt install returned non-zero (see output)"
  # Register the freshly-installed driver/NVENC userspace libs in the loader cache NOW.
  # The nvidia package's ldconfig dpkg-trigger can be DEFERRED, which left libnvidia-encode
  # out of the cache right after install → the verification block's `libnvidia-encode` and
  # `ffmpeg -encoders | grep nvenc` checks false-negatived on the live L4 box even though
  # NVENC was fully present (Ubuntu ffmpeg hides HW encoders when the lib isn't loadable).
  # A reboot also fixes it, but an explicit ldconfig makes the same-run verification honest.
  ldconfig
  # Distinguish a genuine DKMS build failure from a mere reboot-pending state — they
  # need different fixes, and reporting one as the other wastes an operator's time.
  if nvidia-smi >/dev/null 2>&1; then
    ok "driver loaded ($(nvidia-smi --query-gpu=name --format=csv,noheader | head -1))"
  elif dkms status 2>/dev/null | grep -qi 'nvidia.*installed' || modinfo nvidia >/dev/null 2>&1; then
    warn "driver module BUILT but not loaded — reboot, then re-run provision.sh"
  else
    warn "NVIDIA kernel module BUILD FAILED (not just a reboot). Check: dkms status ;"
    warn "  dmesg | grep -i nvidia ; ensure linux-headers-\$(uname -r) is installed."
  fi
fi
# Headless virtual display: let X start on the GPU with NO monitor attached, so OBS's
# OpenGL compositor + browser source get GPU acceleration (NVENC itself is via
# libnvidia-encode and independent of the X display). nvidia-xconfig is NOT shipped
# with the open driver, so write /etc/X11/xorg.conf by hand. Pin a SINGLE resolution
# (Virtual == the one mode): a multi-res Virtual larger than the mode makes X place a
# 1920x1080 viewport at a +offset inside a bigger framebuffer, which desyncs RustDesk's
# absolute mouse mapping (the box's left half went dead). BusID is read live from lspci
# (it differs per instance). (#395, live-verified.)
if has_nvidia_gpu; then
  bus_id="$(gpu_pci_bus_id || true)"
  if [ -z "$bus_id" ]; then
    warn "could not resolve the NVIDIA PCI BusID from lspci — skipping xorg.conf"
  elif [ -f /etc/X11/xorg.conf ] && ! grep -q 'racecast headless X' /etc/X11/xorg.conf; then
    warn "/etc/X11/xorg.conf exists and is not ours — leaving it untouched"
  else
    write_headless_xorg "$bus_id"
    ok "xorg.conf written (headless 1080p on $bus_id)"
  fi
fi

# ---------------------------------------------------------------------------
log "3/10  xfce desktop + autologin (OBS needs a real X11 session)"
apt-get install -y xfce4 xfce4-goodies lightdm
# xfce as the lightdm session + autologin as the racecast user, so an X session for
# `racecast` comes up on :0 at boot. This is the session RustDesk mirrors and the one OBS
# autostarts into — so the remote desktop and OBS both run as `racecast`, matching the
# install tree's owner. (autologin-user below = $USER_NAME = racecast.)
if [ -n "$USER_NAME" ]; then
  install -d -m 0755 /etc/lightdm/lightdm.conf.d
  cat > /etc/lightdm/lightdm.conf.d/50-racecast-autologin.conf <<EOF
[Seat:*]
autologin-user=$USER_NAME
autologin-user-timeout=0
user-session=xfce
EOF
  ok "autologin configured for $USER_NAME"
  write_gui_autostart "$(getent passwd "$USER_NAME" | cut -d: -f6)" "$USER_NAME"
  log "   GUI autostart written (OBS + Discord launch with the session; takes effect next boot)"
else
  warn "no login user detected — set autologin manually after first SSH"
fi

# ---------------------------------------------------------------------------
log "4/10  Firefox (deb from Mozilla APT, not snap — snap confinement breaks cookie export)"
ff="$(command -v firefox || true)"
if [ -n "$ff" ] && ! readlink -f "$ff" | grep '/snap/' >/dev/null; then
  ok "non-snap Firefox already present"
else
  install -d -m 0755 /etc/apt/keyrings
  wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O /etc/apt/keyrings/packages.mozilla.org.asc
  echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" \
    > /etc/apt/sources.list.d/mozilla.list
  printf 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n' \
    > /etc/apt/preferences.d/mozilla
  apt-get update
  apt-get install -y firefox
  ok "Firefox (deb) installed"
fi

# ---------------------------------------------------------------------------
log "5/10  RustDesk (remote desktop over the tailnet) — install + auto-configure"
if have rustdesk; then
  ok "RustDesk already present"
else
  deb="/tmp/rustdesk-${RUSTDESK_VERSION}.deb"
  curl -fsSL "https://github.com/rustdesk/rustdesk/releases/download/${RUSTDESK_VERSION}/rustdesk-${RUSTDESK_VERSION}-x86_64.deb" -o "$deb"
  apt-get install -y "$deb"
  ok "RustDesk ${RUSTDESK_VERSION} installed"
fi
systemctl enable --now rustdesk >/dev/null 2>&1 || true
# Password/ID/direct-IP need the graphical session (post first-boot), so we generate the
# password now (root-only) and install a first-boot oneshot that finishes the config and
# writes the connection info. RUSTDESK_PASSWORD overrides the generated one. No GUI step.
install -d -m 0700 /etc/racecast
if [ ! -s /etc/racecast/rustdesk-password ]; then
  printf '%s' "${RUSTDESK_PASSWORD:-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16)}" \
    > /etc/racecast/rustdesk-password
  chmod 0600 /etc/racecast/rustdesk-password
fi
write_rustdesk_setup_helper "$USER_NAME"
cat > /etc/systemd/system/racecast-rustdesk-setup.service <<EOF
[Unit]
Description=racecast: configure RustDesk (password + direct IP) once the desktop is up
After=graphical.target
Wants=graphical.target
ConditionPathExists=!/var/lib/racecast/rustdesk-configured

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/racecast-rustdesk-setup
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
EOF
systemctl enable racecast-rustdesk-setup.service >/dev/null 2>&1 || true
ok "RustDesk auto-config armed — on first boot the ID + password land in ~$USER_NAME/rustdesk-access.txt"

# ---------------------------------------------------------------------------
log "6/10  passwordless sudo"
if [ -n "$USER_NAME" ]; then
  f="/etc/sudoers.d/90-racecast"
  echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" > "$f"
  chmod 0440 "$f"
  if visudo -cf "$f" >/dev/null 2>&1; then
    ok "passwordless sudo for $USER_NAME"
  else
    rm -f "$f"; warn "sudoers validation failed — drop-in removed"
  fi
else
  warn "no login user detected — passwordless sudo deferred (re-run under sudo after first SSH)"
fi

# ---------------------------------------------------------------------------
log "7/10  racecast binary (installed straight into the racecast user's home — user-owned tree)"
# The frozen binary resolves profiles/ + runtime/ next to itself, and the relay writes
# runtime state, so the tree must be owned by the event user (NOT root). Extract the
# tarball DIRECTLY into ~racecast (its top level is the `racecast` binary + .env.example,
# so the binary lands at ~racecast/racecast, with profiles/ + runtime/ created alongside
# — no redundant ~racecast/racecast/ nesting: the HOME is the install root). Steps 8-9
# run install-tools/install-apps as this user, so every event operation is sudo-free.
if [ -z "$USER_NAME" ]; then
  warn "no login user detected — racecast install deferred (re-run under sudo after first SSH)"
elif have racecast; then
  ok "racecast already on PATH ($(sudo -u "$USER_NAME" racecast --version 2>/dev/null | head -1))"
else
  case "$(uname -m)" in
    aarch64|arm64) asset="racecast-linux-arm64.tar.gz" ;;
    *)             asset="racecast-linux.tar.gz" ;;
  esac
  tag="${RACECAST_TAG:-latest}"
  if [ "$tag" = "latest" ]; then
    url="https://github.com/${RACECAST_REPO}/releases/latest/download/${asset}"
  else
    url="https://github.com/${RACECAST_REPO}/releases/download/${tag}/${asset}"
  fi
  user_home="$(getent passwd "$USER_NAME" | cut -d: -f6)"
  user_group="$(id -gn "$USER_NAME")"   # not necessarily == USER_NAME (non-UPG distros)
  curl -fsSL "$url" -o /tmp/racecast.tar.gz
  tar -xzf /tmp/racecast.tar.gz -C "$user_home"
  chown -R "$USER_NAME:$user_group" "$user_home"
  ln -sf "$user_home/racecast" /usr/local/bin/racecast
  ok "racecast installed in $user_home ($(sudo -u "$USER_NAME" racecast --version 2>/dev/null | head -1))"
fi

# Pre-create the FULL ~/.config/obs-studio/plugins tree (racecast-owned) BEFORE
# install-apps runs. install-apps' obs-pipewire-audio step writes the plugin .so here
# AS the racecast user; on the #421 live box a root sub-step of install-apps had
# created ~/.config first (root-owned) → the plugin install EACCES'd. Owning the whole
# leaf tree up front makes this robust: even if a later root sub-step re-owns ~/.config
# itself, its 0755 grants SEARCH (x) to the racecast user, who still writes into the
# racecast-owned leaf. `install -d` only sets ownership on dirs it CREATES, so a
# pre-existing (root-owned) parent is fine as long as it stays searchable.
if [ -n "$USER_NAME" ]; then
  uh="$(getent passwd "$USER_NAME" | cut -d: -f6)"
  grp="$(id -gn "$USER_NAME")"
  install -d -o "$USER_NAME" -g "$grp" -m 0755 \
    "$uh/.config" "$uh/.config/obs-studio" "$uh/.config/obs-studio/plugins"
fi

# ---------------------------------------------------------------------------
log "8/10  racecast install-tools (yt-dlp / streamlink / ffmpeg / deno) — as $USER_NAME"
# Run as the user so the toolchain lands under the user-owned ~racecast/runtime.
# `|| warn` so a partial toolchain hiccup does NOT trip `set -e` and abort provision
# before the Tailscale step + the verification block (which report exactly what to
# re-run). The verification block below is the source of truth for tool presence.
if [ -n "$USER_NAME" ] && have racecast; then
  sudo -u "$USER_NAME" -H racecast install-tools \
    || warn "install-tools reported issues — see the verification block below"
  ok "install-tools step done"
else
  warn "racecast not installed / no login user — skipping install-tools"
fi

# ---------------------------------------------------------------------------
log "9/10  racecast install-apps (OBS + Browser Source + PipeWire audio plugin, Tailscale, Companion, Discord) — as $USER_NAME"
# install-apps calls `sudo apt-get` internally — the passwordless sudo from step 6 makes
# that work while keeping the racecast tree user-owned.
# `|| warn`: install-apps returns non-zero when ANY optional sub-step fails (e.g. the
# obs-pipewire-audio plugin) — that must NOT abort provision via `set -e`. The failed
# steps are named in install-apps' own output and re-checked in the verification block.
if [ -n "$USER_NAME" ] && have racecast; then
  sudo -u "$USER_NAME" -H racecast install-apps --yes \
    || warn "install-apps reported issues — see the verification block below"
  ok "install-apps step done"
  # Repair any root-owned droppings a sudo sub-step of install-apps may have left in
  # the racecast tree, so every later runtime write (relay, cookies, OBS config) stays
  # EACCES-free. Best-effort — never abort provision on a chown hiccup.
  uh="$(getent passwd "$USER_NAME" | cut -d: -f6)"
  chown -R "$USER_NAME:$(id -gn "$USER_NAME")" "$uh/.config" 2>/dev/null || true
else
  warn "racecast not installed / no login user — skipping install-apps"
fi

# ---------------------------------------------------------------------------
log "10/10  Tailscale join (REQUIRED — the tailnet is the box's trust boundary)"
# Joining the tailnet is NOT optional: it is the only way your laptop reaches the Control
# Center / relay / RustDesk privately (the relay's control port is never exposed publicly).
# We DO the join here rather than just suggesting it:
#   - TS_AUTHKEY set        -> unattended join (CI / startup-script).
#   - interactive terminal  -> run `tailscale up` NOW; it prints a login URL you open in
#                              your LAPTOP browser to approve the box. Provisioning WAITS
#                              here until you finish (browser auth — no key committed to git).
#   - non-interactive, no key (detached / startup-script) -> can't prompt for browser auth;
#                              print the one command to run once and let the verification
#                              block flag the box as not-yet-joined. This is the ONLY branch
#                              that leaves the REQUIRED join for the operator to finish.
if tailscale status >/dev/null 2>&1; then
  ok "already joined the tailnet ($(tailscale ip -4 2>/dev/null | head -1))"
elif [ -n "${TS_AUTHKEY:-}" ]; then
  tailscale up --ssh --authkey "$TS_AUTHKEY" --hostname racecast-box
  ok "joined the tailnet unattended ($(tailscale ip -4 2>/dev/null | head -1))"
elif [ -t 0 ]; then
  log "   ACTION REQUIRED — approve this box into your tailnet."
  log "   'tailscale up' prints a https://login.tailscale.com/… URL below; open it in your"
  log "   LAPTOP browser and approve. Provisioning WAITS here until you finish."
  if tailscale up --ssh --hostname racecast-box; then
    ok "joined the tailnet ($(tailscale ip -4 2>/dev/null | head -1))"
  else
    warn "tailscale up did not complete — re-run: sudo tailscale up --ssh --hostname racecast-box"
  fi
else
  warn "REQUIRED join not done: no TS_AUTHKEY and no interactive terminal (detached run)."
  warn "The box is NOT reachable over the tailnet yet. Run this once and approve the URL"
  warn "in your LAPTOP browser:"
  echo "      sudo tailscale up --ssh --hostname racecast-box"
fi

# ---------------------------------------------------------------------------
log "verification — every REQUIRED component below must be PRESENT. There are no optional"
log "steps: a red PRESENCE line means the box is NOT fully equipped. provision is idempotent"
log "— fix the cause and re-run; nothing is skipped on a real (GPU) event box."
rc=0
ldconfig 2>/dev/null || true   # settle the loader cache so the GPU/NVENC presence checks
                               # below are honest even if a dpkg ldconfig-trigger was deferred
pw_home="$(getent passwd "$USER_NAME" | cut -d: -f6)"
mbin="$pw_home/runtime/bin"          # racecast-managed tool bin (yt-dlp / streamlink / deno)

# --- feed toolchain (install-tools): yt-dlp/streamlink/deno are managed binaries in
#     ~racecast/runtime/bin (not on root's PATH); ffmpeg comes from apt on PATH ---
if [ -x "$mbin/yt-dlp" ];     then ok "yt-dlp: $("$mbin/yt-dlp" --version 2>/dev/null | head -1) (managed)"; else warn "yt-dlp: MISSING — re-run install-tools"; rc=1; fi
if [ -x "$mbin/streamlink" ]; then ok "streamlink: $("$mbin/streamlink" --version 2>/dev/null | head -1) (managed venv)"; else warn "streamlink: MISSING — re-run install-tools"; rc=1; fi
if [ -x "$mbin/deno" ];       then ok "deno: $("$mbin/deno" --version 2>/dev/null | head -1) (managed)"; else warn "deno: MISSING — re-run install-tools"; rc=1; fi
if have ffmpeg;               then ok "ffmpeg: present"; else warn "ffmpeg: MISSING — re-run install-tools"; rc=1; fi

# --- racecast + desktop + remote-access layer ---
if have racecast;             then ok "racecast: $(racecast --version 2>/dev/null | head -1)"; else warn "racecast: MISSING"; rc=1; fi
ff2="$(command -v firefox || true)"
if [ -n "$ff2" ] && ! readlink -f "$ff2" | grep -q '/snap/'; then ok "firefox: deb build"; else warn "firefox: MISSING or snap (cookie export needs the deb build)"; rc=1; fi
if have rustdesk;             then ok "rustdesk: present"; else warn "rustdesk: MISSING — re-run step 5"; rc=1; fi
if dpkg -s lightdm >/dev/null 2>&1; then ok "lightdm/xfce desktop: installed"; else warn "lightdm: MISSING — re-run step 3"; rc=1; fi

# --- broadcast apps (install-apps): OBS + BOTH plugins, Companion, Discord, Tailscale ---
if have obs;                  then ok "obs: installed"; else warn "obs: MISSING — re-run install-apps"; rc=1; fi
obsbrowser=""
for p in /usr/lib/x86_64-linux-gnu/obs-plugins/obs-browser.so /usr/lib/obs-plugins/obs-browser.so "$pw_home"/.config/obs-studio/plugins/obs-browser/bin/64bit/obs-browser.so; do
  [ -f "$p" ] && obsbrowser="$p" && break
done
if [ -n "$obsbrowser" ];      then ok "OBS Browser Source plugin: present (HUD/timer overlays)"; else warn "OBS Browser Source plugin: MISSING — the relay HUD/timer overlays need it"; rc=1; fi
if [ -f "$pw_home/.config/obs-studio/plugins/linux-pipewire-audio/bin/64bit/linux-pipewire-audio.so" ]; then ok "OBS PipeWire audio plugin: present (Discord audio source)"; else warn "OBS PipeWire audio plugin: MISSING — re-run install-apps"; rc=1; fi
if [ -e /opt/companion ] || [ -e /etc/systemd/system/companion.service ]; then ok "companion: installed (companion-pi service)"; else warn "companion: MISSING — re-run install-apps"; rc=1; fi
if [ -e /usr/bin/discord ] || [ -e /usr/share/discord ]; then ok "discord: installed"; else warn "discord: MISSING — re-run install-apps"; rc=1; fi
if have tailscale;            then ok "tailscale: installed"; else warn "tailscale: MISSING — re-run install-apps"; rc=1; fi

# --- GPU stack: REQUIRED on a real event box; only the CPU dry-run (has_nvidia_gpu=false)
#     legitimately has no GPU. On a GPU box a missing driver/NVENC IS a hard failure. ---
if has_nvidia_gpu; then
  if nvidia-smi >/dev/null 2>&1; then ok "nvidia driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1)"; else warn "nvidia driver: MISSING — nvidia-smi fails (reboot + re-run, or check the DKMS build)"; rc=1; fi
  if ldconfig -p | grep -q nvidia-encode; then ok "libnvidia-encode: present (NVENC)"; else warn "libnvidia-encode: MISSING — NVENC needs it"; rc=1; fi
  if have ffmpeg && ffmpeg -hide_banner -encoders 2>/dev/null | grep -q nvenc; then ok "ffmpeg NVENC encoders: present"; else warn "ffmpeg NVENC encoders: MISSING"; rc=1; fi
else
  warn "no NVIDIA GPU on this host — GPU stack (driver/NVENC/X-on-GPU) NOT verified. This is"
  warn "the CPU dry-run only; a real event box MUST run on a GPU box (has_nvidia_gpu=true)."
fi

# --- post-reboot / post-join STATE (an operational step still to do — NOT a missing
#     component, so these advise but do not fail the equipped-ness gate) ---
if tailscale status >/dev/null 2>&1; then ok "tailnet: joined ($(tailscale ip -4 2>/dev/null | head -1))"; else warn "tailnet: not joined yet — complete the REQUIRED browser-auth join (step 10)"; fi
if pgrep -x Xorg >/dev/null 2>&1; then ok "X server: running"; else warn "X server: not running yet — reboot to start the racecast autologin session (RustDesk needs it)"; fi
if has_nvidia_gpu && pgrep -x Xorg >/dev/null 2>&1; then
  if DISPLAY=:0 glxinfo 2>/dev/null | grep -qi nvidia; then ok "OpenGL renderer: NVIDIA (X is on the GPU)"; else warn "OpenGL renderer not NVIDIA yet — re-check after reboot: DISPLAY=:0 glxinfo -B"; fi
fi

echo
if [ "$rc" -eq 0 ]; then
  log "provision.sh complete — box FULLY EQUIPPED (every required component present)."
  echo "      Event stack is owned by '$USER_NAME' (its home: $(getent passwd "$USER_NAME" | cut -d: -f6))."
  echo "      Log in as that user directly — 'gcloud compute ssh $USER_NAME@racecast-box' —"
  echo "      then run racecast plainly: 'racecast preflight', 'racecast event start', …"
  echo "      Remaining operational steps (if warned above): finish the tailnet join + reboot"
  echo "      for the GPU X session (the reboot also auto-configures RustDesk)."
  echo "      After the reboot: 'cat ~$USER_NAME/rustdesk-access.txt' for the RustDesk ID + password."
  echo "      Then: per-league onboarding (profile + cookies + setup + OBS import)."
else
  warn "provision.sh finished with MISSING components (red PRESENCE lines above) — the box is"
  warn "NOT fully equipped. Fix the cause and re-run provision; it is idempotent and will"
  warn "install only what is still missing. Do NOT proceed to an event with a red line."
fi
exit "$rc"
