#!/usr/bin/env bash
# provision.sh — one-shot machine-layer provisioning for a GCP GPU box (Ubuntu 24.04)
# for the racecast cloud-producer spike (#395).
#
# Installs everything racecast does NOT cover — NVIDIA driver, xfce desktop,
# Firefox (deb, not snap), RustDesk, passwordless sudo, Tailscale join — then delegates
# the toolchain + applications to the racecast binary (install-tools / install-apps).
#
# Idempotent: every step is existence-/stamp-gated; safe to re-run after a failure.
# Runs as root: `sudo ./provision.sh`, or as a GCP startup-script (instance metadata).
#
# Optional environment:
#   TS_AUTHKEY        Tailscale reusable/ephemeral pre-auth key for unattended join.
#                     NEVER commit this. When unset, the browser-auth command is printed.
#   RACECAST_TAG      racecast release tag to install (default: latest = latest STABLE
#                     release). Set to `preview-main` to install the current main
#                     preview build — needed until the Linux install-tools/install-apps
#                     fixes land in a stable release: apt-update-first (#408/#412) AND
#                     the streamlink-venv >=8.2.0 + obs-pipewire-audio plugin installs
#                     (#395). Without them a fresh box gets a too-old streamlink (every
#                     cookie'd YouTube feed aborts) and no Discord audio plugin.
#                     `latest` never selects a pre-release, so this is opt-in.
#   RUSTDESK_VERSION  RustDesk release to install (default: pinned below; check for newer).
#
# NOT handled here — per-league onboarding the operator does once per league:
#   racecast profiles, cookies, `racecast setup`, OBS scene import, RustDesk password.

set -euo pipefail

RUSTDESK_VERSION="${RUSTDESK_VERSION:-1.3.8}"
RACECAST_REPO="jegr78/gt-endurance-racing-broadcast"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '  \033[1;32mOK\033[0m  %s\n' "$*"; }
warn() { printf '  \033[1;33m!!\033[0m  %s\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }
has_nvidia_gpu() { lspci 2>/dev/null | grep -i 'nvidia' >/dev/null; }   # SIGPIPE-safe (no -q early close under pipefail); false on a CPU-only dry-run box

# Resolve the NVIDIA card's PCI slot (DDDD:BB:DD.F, hex) to an Xorg BusID
# (PCI:bus:dev:fn, DECIMAL). Differs per instance, so read it live. Empty -> caller warns.
gpu_pci_bus_id() {
  local slot bus dev fn
  slot="$(lspci -D 2>/dev/null | grep -iE 'nvidia' | grep -iE 'VGA|3D|Display' | head -1 | awk '{print $1}')"
  [ -n "$slot" ] || return 1
  slot="${slot#*:}"          # strip domain -> BB:DD.F
  bus="${slot%%:*}"          # BB
  dev="${slot#*:}"; dev="${dev%%.*}"   # DD
  fn="${slot#*.}"            # F
  printf 'PCI:%d:%d:%d' "0x$bus" "0x$dev" "0x$fn"
}

# Write a headless Xorg config: a single 1920x1080 mode with a matching Virtual size
# (NOT larger — a bigger Virtual creates a +offset viewport that breaks RustDesk's
# absolute pointer mapping), forcing a virtual DFP so X comes up with no monitor.
write_headless_xorg() {
  local bus_id="$1"
  cat > /etc/X11/xorg.conf <<EOF
# racecast headless X (generated by provision.sh) — single 1920x1080, no monitor.
Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
EndSection

Section "Device"
    Identifier "Device0"
    Driver     "nvidia"
    BusID      "$bus_id"
    Option     "AllowEmptyInitialConfiguration" "true"
    Option     "ConnectedMonitor" "DFP-0"
    Option     "ModeValidation" "AllowNonEdidModes"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    HorizSync  28.0 - 80.0
    VertRefresh 48.0 - 75.0
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Device0"
    Monitor    "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Depth  24
        Modes  "1920x1080"
        Virtual 1920 1080
    EndSubSection
EndSection
EOF
}

# GUI autostart so `racecast event start` over SSH finds OBS + Discord already
# running in the autologin session (belt-and-suspenders with event start's
# DISPLAY=:0 launch). Harmless if a binary is absent — the entry just no-ops.
write_gui_autostart() {
  local user_home="$1" user_name="$2"
  install -d -o "$user_name" -g "$user_name" "$user_home/.config/autostart"
  cat > "$user_home/.config/autostart/racecast-obs.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=OBS Studio (racecast)
Exec=obs
X-GNOME-Autostart-enabled=true
EOF
  cat > "$user_home/.config/autostart/racecast-discord.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=Discord (racecast)
Exec=discord
X-GNOME-Autostart-enabled=true
EOF
  chown "$user_name:$user_name" \
    "$user_home/.config/autostart/racecast-obs.desktop" \
    "$user_home/.config/autostart/racecast-discord.desktop"
}

if [ "$(id -u)" -ne 0 ]; then
  echo "provision.sh must run as root (use: sudo ./provision.sh)" >&2
  exit 1
fi

# The human login user (for sudoers + desktop autologin). Under `sudo` that is
# $SUDO_USER; as a boot-time startup-script no human exists yet — fall back to the
# first real (uid>=1000) account, else defer (the GCP guest agent's google-sudoers
# already grants NOPASSWD until a re-run under `sudo` sets the explicit rule).
target_user() {
  if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    printf '%s' "$SUDO_USER"; return 0
  fi
  getent passwd | awk -F: '$3>=1000 && $3<65534 {print $1; exit}'
}
USER_NAME="$(target_user || true)"

# ---------------------------------------------------------------------------
log "1/10  APT base + upgrade"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y upgrade
# python3-venv + python3-pip: racecast install-tools builds an isolated streamlink
# venv on Linux (apt's streamlink is too old for --http-cookies-file, #350/#395).
# mesa-utils: glxinfo for the headless-X verification; x11-utils: xdpyinfo debug aid.
apt-get install -y curl python3 python3-venv python3-pip ca-certificates wget gnupg pciutils mesa-utils x11-utils
ok "base packages present"

# ---------------------------------------------------------------------------
log "2/10  NVIDIA driver (nvidia-open via CUDA apt repo) + headless X config"
# Why NOT GoogleCloudPlatform/install_gpu_driver.py: it pins driver 550.54.15, whose
# proprietary kernel modules FAIL to build against Ubuntu 24.04's current HWE kernel
# (6.17) — the box hit exactly this. The NVIDIA CUDA apt repo's `nvidia-open` (open
# kernel modules, DKMS-built) builds cleanly on new kernels. (#395, live-verified.)
if ! has_nvidia_gpu; then
  warn "no NVIDIA GPU on this host — skipping driver + xorg (CPU dry-run mode)"
elif nvidia-smi >/dev/null 2>&1; then
  ok "driver already loaded ($(nvidia-smi --query-gpu=name --format=csv,noheader | head -1))"
else
  case "$(uname -m)" in
    aarch64|arm64) cuda_arch="sbsa" ;;
    *)             cuda_arch="x86_64" ;;
  esac
  if [ ! -f /etc/apt/sources.list.d/cuda-ubuntu2404-"$cuda_arch".list ] \
     && ! apt-key list 2>/dev/null | grep -qi cuda; then
    curl -fsSL "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/${cuda_arch}/cuda-keyring_1.1-1_all.deb" -o /tmp/cuda-keyring.deb
    dpkg -i /tmp/cuda-keyring.deb
    apt-get update
  fi
  apt-get install -y nvidia-open || warn "nvidia-open apt install returned non-zero (see output)"
  # Distinguish a genuine DKMS build failure from a mere reboot-pending state — they
  # need different fixes, and reporting one as the other wastes an operator's time.
  if nvidia-smi >/dev/null 2>&1; then
    ok "driver loaded ($(nvidia-smi --query-gpu=name --format=csv,noheader | head -1))"
  elif dkms status 2>/dev/null | grep -qi 'nvidia.*installed' || modinfo nvidia >/dev/null 2>&1; then
    warn "driver module BUILT but not loaded — reboot, then re-run provision.sh"
  else
    warn "NVIDIA kernel module BUILD FAILED (not just a reboot). Check: dkms status ;"
    warn "  dmesg | grep -i nvidia ; ensure linux-headers-\$(uname -r) is installed."
  fi
fi
# Headless virtual display: let X start on the GPU with NO monitor attached, so OBS's
# OpenGL compositor + browser source get GPU acceleration (NVENC itself is via
# libnvidia-encode and independent of the X display). nvidia-xconfig is NOT shipped
# with the open driver, so write /etc/X11/xorg.conf by hand. Pin a SINGLE resolution
# (Virtual == the one mode): a multi-res Virtual larger than the mode makes X place a
# 1920x1080 viewport at a +offset inside a bigger framebuffer, which desyncs RustDesk's
# absolute mouse mapping (the box's left half went dead). BusID is read live from lspci
# (it differs per instance). (#395, live-verified.)
if has_nvidia_gpu; then
  bus_id="$(gpu_pci_bus_id || true)"
  if [ -z "$bus_id" ]; then
    warn "could not resolve the NVIDIA PCI BusID from lspci — skipping xorg.conf"
  elif [ -f /etc/X11/xorg.conf ] && ! grep -q 'racecast headless X' /etc/X11/xorg.conf; then
    warn "/etc/X11/xorg.conf exists and is not ours — leaving it untouched"
  else
    write_headless_xorg "$bus_id"
    ok "xorg.conf written (headless 1080p on $bus_id)"
  fi
fi

# ---------------------------------------------------------------------------
log "3/10  xfce desktop + autologin (OBS needs a real X11 session)"
apt-get install -y xfce4 xfce4-goodies lightdm
# xfce as the lightdm session + autologin for the login user, so an X session comes up
# on boot for RustDesk to attach to.
if [ -n "$USER_NAME" ]; then
  install -d -m 0755 /etc/lightdm/lightdm.conf.d
  cat > /etc/lightdm/lightdm.conf.d/50-racecast-autologin.conf <<EOF
[Seat:*]
autologin-user=$USER_NAME
autologin-user-timeout=0
user-session=xfce
EOF
  ok "autologin configured for $USER_NAME"
  write_gui_autostart "$(getent passwd "$USER_NAME" | cut -d: -f6)" "$USER_NAME"
  log "   GUI autostart written (OBS + Discord launch with the session; takes effect next boot)"
else
  warn "no login user detected — set autologin manually after first SSH"
fi

# ---------------------------------------------------------------------------
log "4/10  Firefox (deb from Mozilla APT, not snap — snap confinement breaks cookie export)"
ff="$(command -v firefox || true)"
if [ -n "$ff" ] && ! readlink -f "$ff" | grep '/snap/' >/dev/null; then
  ok "non-snap Firefox already present"
else
  install -d -m 0755 /etc/apt/keyrings
  wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O /etc/apt/keyrings/packages.mozilla.org.asc
  echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" \
    > /etc/apt/sources.list.d/mozilla.list
  printf 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n' \
    > /etc/apt/preferences.d/mozilla
  apt-get update
  apt-get install -y firefox
  ok "Firefox (deb) installed"
fi

# ---------------------------------------------------------------------------
log "5/10  RustDesk (remote desktop over the tailnet)"
if have rustdesk; then
  ok "RustDesk already present"
else
  deb="/tmp/rustdesk-${RUSTDESK_VERSION}.deb"
  curl -fsSL "https://github.com/rustdesk/rustdesk/releases/download/${RUSTDESK_VERSION}/rustdesk-${RUSTDESK_VERSION}-x86_64.deb" -o "$deb"
  apt-get install -y "$deb"
  ok "RustDesk ${RUSTDESK_VERSION} installed (set the password + 'direct IP access' in the GUI)"
fi

# ---------------------------------------------------------------------------
log "6/10  passwordless sudo"
if [ -n "$USER_NAME" ]; then
  f="/etc/sudoers.d/90-racecast"
  echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" > "$f"
  chmod 0440 "$f"
  if visudo -cf "$f" >/dev/null 2>&1; then
    ok "passwordless sudo for $USER_NAME"
  else
    rm -f "$f"; warn "sudoers validation failed — drop-in removed"
  fi
else
  warn "no login user detected — passwordless sudo deferred (re-run under sudo after first SSH)"
fi

# ---------------------------------------------------------------------------
log "7/10  racecast binary (installed into the login user's home — user-owned tree)"
# The frozen binary resolves profiles/ + runtime/ next to itself, and the relay writes
# runtime state, so the tree must be owned by the event user (NOT root). Install into
# ~USER/racecast and run install-tools/install-apps as that user (steps 8-9), so every
# event operation (profile switch, cookies, relay) runs without sudo.
if [ -z "$USER_NAME" ]; then
  warn "no login user detected — racecast install deferred (re-run under sudo after first SSH)"
elif have racecast; then
  ok "racecast already on PATH ($(sudo -u "$USER_NAME" racecast --version 2>/dev/null | head -1))"
else
  case "$(uname -m)" in
    aarch64|arm64) asset="racecast-linux-arm64.tar.gz" ;;
    *)             asset="racecast-linux.tar.gz" ;;
  esac
  tag="${RACECAST_TAG:-latest}"
  if [ "$tag" = "latest" ]; then
    url="https://github.com/${RACECAST_REPO}/releases/latest/download/${asset}"
  else
    url="https://github.com/${RACECAST_REPO}/releases/download/${tag}/${asset}"
  fi
  user_home="$(getent passwd "$USER_NAME" | cut -d: -f6)"
  user_group="$(id -gn "$USER_NAME")"   # not necessarily == USER_NAME (non-UPG distros)
  curl -fsSL "$url" -o /tmp/racecast.tar.gz
  install -d -o "$USER_NAME" -g "$user_group" -m 0755 "$user_home/racecast"
  tar -xzf /tmp/racecast.tar.gz -C "$user_home/racecast"
  chown -R "$USER_NAME:$user_group" "$user_home/racecast"
  ln -sf "$user_home/racecast/racecast" /usr/local/bin/racecast
  ok "racecast installed at $user_home/racecast ($(sudo -u "$USER_NAME" racecast --version 2>/dev/null | head -1))"
fi

# ---------------------------------------------------------------------------
log "8/10  racecast install-tools (yt-dlp / streamlink / ffmpeg / deno) — as $USER_NAME"
# Run as the user so the toolchain lands under the user-owned ~USER/racecast/runtime.
if [ -n "$USER_NAME" ] && have racecast; then
  sudo -u "$USER_NAME" -H racecast install-tools
  ok "toolchain installed"
else
  warn "racecast not installed / no login user — skipping install-tools"
fi

# ---------------------------------------------------------------------------
log "9/10  racecast install-apps (OBS + Browser Source + PipeWire audio plugin, Tailscale, Companion, Discord) — as $USER_NAME"
# install-apps calls `sudo apt-get` internally — the passwordless sudo from step 6 makes
# that work while keeping the racecast tree user-owned.
if [ -n "$USER_NAME" ] && have racecast; then
  sudo -u "$USER_NAME" -H racecast install-apps --yes
  ok "applications installed"
else
  warn "racecast not installed / no login user — skipping install-apps"
fi

# ---------------------------------------------------------------------------
log "10/10  Tailscale join"
if tailscale status >/dev/null 2>&1; then
  ok "already joined the tailnet ($(tailscale ip -4 2>/dev/null | head -1))"
elif [ -n "${TS_AUTHKEY:-}" ]; then
  tailscale up --ssh --authkey "$TS_AUTHKEY" --hostname racecast-box
  ok "joined the tailnet unattended"
else
  warn "no TS_AUTHKEY set — run this once to join:"
  echo "      sudo tailscale up --ssh --hostname racecast-box"
fi

# ---------------------------------------------------------------------------
log "verification"
rc=0
if nvidia-smi >/dev/null 2>&1; then ok "nvidia-smi: GPU present"; else warn "nvidia-smi: FAIL (reboot + re-run)"; rc=1; fi
if have ffmpeg && ffmpeg -hide_banner -encoders 2>/dev/null | grep nvenc >/dev/null; then ok "ffmpeg: NVENC encoders present"; else warn "ffmpeg NVENC: FAIL"; rc=1; fi
if ldconfig -p | grep nvidia-encode >/dev/null; then ok "libnvidia-encode present"; else warn "libnvidia-encode: not found (NVENC needs it)"; fi
ff2="$(command -v firefox || true)"
if [ -n "$ff2" ] && ! readlink -f "$ff2" | grep '/snap/' >/dev/null; then ok "firefox: deb build"; else warn "firefox: missing or snap"; rc=1; fi
if have racecast; then ok "racecast: $(racecast --version 2>/dev/null | head -1)"; else warn "racecast: FAIL"; rc=1; fi
if have obs; then ok "obs: installed"; else warn "obs: not on PATH (check install-apps output)"; fi
if [ -n "$USER_NAME" ]; then
  pw_home="$(getent passwd "$USER_NAME" | cut -d: -f6)"
  if [ -f "$pw_home/.config/obs-studio/plugins/linux-pipewire-audio/bin/64bit/linux-pipewire-audio.so" ]; then
    ok "OBS PipeWire audio plugin: installed (Discord audio source)"
  else
    warn "OBS PipeWire audio plugin: not found — Discord interview audio can't capture (re-run install-apps)"
  fi
fi
if [ -n "$USER_NAME" ]; then
  # streamlink is the user-managed venv (~USER/racecast/runtime/bin), not on root's
  # PATH — resolve it there. `racecast preflight` owns the authoritative >=8.2.0 floor.
  sl="$pw_home/racecast/runtime/bin/streamlink"
  if [ -x "$sl" ]; then ok "streamlink: $("$sl" --version 2>/dev/null | head -1) (managed venv)";
  else warn "streamlink: managed venv missing — run install-tools; then `racecast preflight`"; fi
fi
if tailscale status >/dev/null 2>&1; then ok "tailscale: up"; else warn "tailscale: not joined (run tailscale up)"; fi
if pgrep -x Xorg >/dev/null 2>&1; then ok "X server: running"; else warn "X server: not running yet (reboot to start the autologin session; RustDesk needs it)"; fi
if has_nvidia_gpu; then
  if DISPLAY=:0 glxinfo 2>/dev/null | grep -i nvidia >/dev/null; then ok "OpenGL renderer: NVIDIA (X is on the GPU)"; else warn "OpenGL renderer not NVIDIA yet — reboot so the X session starts, then re-check: DISPLAY=:0 glxinfo -B"; fi
fi

echo
if [ "$rc" -eq 0 ]; then
  log "provision.sh complete — machine layer ready. Next: per-league onboarding (profile + cookies + racecast setup + OBS import)."
else
  warn "provision.sh finished with issues above — fix and re-run (idempotent)."
fi
exit "$rc"
